config/routes.rb
# -*- encoding : utf-8 -*-
JobsApptopia::Application.routes.draw do
  
  match '/about' => 'pages#about', :as => "about"
  
  devise_for :users

  resources :jobs do
    member do
      put :open
      put :close
      put :restart
      get :preview
      get :publish
      post :payment
    end
  end

  resources :admin do
    member do
      get :dashboard
    end
  end

  root :to => "jobs#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
  
  match "*path" => "pages#404"
end

app/views/admin/dashboard.html.erb
<div class="container">
	<% @jobs.each_with_index do |job, i| %>
		<div class="row-fluid <%= 'apply-info' if job.highlighted == true %>">
			<div class="new-tag pull-left">
				<%= link_to 'NEW', '', :class => 'btn btn-u-mini' if job.elapsed_date < 6%>
			</div>
      <div class="span11 booking-blocks">
        <div style="overflow:hidden;">
        	<h4>
        		<%= link_to job.title, job_path(job), :style => 'float: left;' %>
        		<span class="hour pull-right light-gray"><%= job.elapsed %> ago</span>
        	</h4>
        	<br>
          <h5>
          	<strong><%= job.company_name %> - </strong>
          	<normal><%= job.location %></normal>
          </h5>
          <% description = strip_tags(job.description) %>
          <p class="light-gray"><%= description.slice!(0, 105) %> 
          	<% if description.length > 105 %>
          		...
          	<% end %>
          </p>
        </div>
        <div class="pull-left blog-page blog-item">
         	<ul class="unstyled inline blog-tags pull-left">
          	<%= show_tags(job) %>
          </ul>
        </div>
        <%#= link_to 'How to Apply', '', :class => 'btn btn-u-mini pull-right' %>
      </div>
    </div><!-- Row Fliud for each Job-->
    <%= "<hr>".html_safe if i != @jobs.length-1 %>
  <% end %>
</div>

app/views/admin/index.html.erb
<div style="width: 1150px; float: none; margin: 0px auto;">
  <div class="row-fluid" id="admin">
    <h3>Posted Jobs</h3>
    <div class="span12">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Company Name</th>
            <th>Name of Contact</th>
            <th>Email</th>
            <th>Created</th>
            <th>Live or Expired</th>
            <th>Copy of Invoice</th>
            <th>Job Title</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
        <% @jobs.each do |job| %>
          <tr>
            <td><%= job.company_name %></td>
            <td><%= job.url %></td>
            <td><%#= job.company_email %></td>
            <td><%= job.created_at.to_date %></td>
            <td><%= job.expired ? "Expired" : "Live" %></td>
            <td></td>
            <td><%= job.title %></td>
            <td>
              <%= link_to("<icon class='icon-refresh'>".html_safe, restart_job_path(job), method: :put, :class => 'btn btn-mini') %>
              <%= link_to("<icon class='icon-stop'>".html_safe, job_path(job), :data => { :confirm => "Are you sure?" }, :class => 'btn btn-mini') %>
              <%= link_to("<icon class='icon-remove'>".html_safe, job_path(job), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') %>
              <%= link_to("<icon class='icon-pencil'>".html_safe, edit_job_path(job), :class => 'btn btn-mini') %>
              <%= link_to("Refund".html_safe, :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>