config/routes.rb
# -*- encoding : utf-8 -*-
JobsApptopia::Application.routes.draw do
  
  match '/about' => 'pages#about', :as => "about"
  
  devise_for :users

  resources :jobs do
    member do
      put :open
      put :close
      put :restart
      get :preview
      get :publish
      post :payment
    end
  end

  resources :admin do
    member do
      get :dashboard
    end
  end

  root :to => "jobs#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
  
  match "*path" => "pages#404"
end

app/models/job.rb
# -*- encoding : utf-8 -*-
# == Schema Information
#
# Table name: jobs
#
#  id                :integer          not null, primary key
#  title             :string(255)
#  job_type          :string(255)
#  occupation        :string(255)
#  company_name      :string(255)
#  location          :string(255)
#  url               :string(255)
#  description       :text
#  apply_information :text
#  deadline          :date
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  aasm_state        :string(255)
#

class Job < ActiveRecord::Base
  
  attr_accessor :deadline_forever
  attr_accessible :title, :job_type, :tags, :occupation, :company_name, :company_logo, :url, :location, :description, :apply_information, :highlighted1, :highlighted2, :highlighted3, :payment_method, :card_number, :ccvn, :expire_date, :zipcode

  has_attached_file :company_logo, :styles => { :medium => "150x150>" }, 
    storage: :dropbox,
    dropbox_credentials: Rails.root.join("config/dropbox.yml"),
    default_url: "/assets/missing.jpg", 
    path: "upload/:class/:attachment/:style/:filename"

  extend Searchable
  searchable_by :title, :job_type, :tags, :company_name, :url, :location, :description, :apply_information
  
  validates_presence_of :title
  validates_presence_of :job_type
  validates_presence_of :company_name
  validates_presence_of :location
  validates_presence_of :description
  validates_presence_of :apply_information
  # validates_presence_of :owner
  
  # validates_format_of :description, :with => /(ruby|rails)/i, :message => "Doesn't seem to be a Ruby or Rails related job"
  TAGS = ['','jquery', 'sql', 'c#', 'python', 'java', 'c++', 'objective C', 'ruby on rails',
          'android', 'php', 'perl', 'mysql', 'jquery', 'html5', 'css', 'mongo db', 'oracle']

  JOB_TYPE = ['Full-time', 'Part-time', 'App project']
  # OCCUPATION = ['Web back-end', 'Web front-end', 'Web-design',
  #               'QA/Testing', 'Other']
  SEARCH_TERMS = ['Date Posted', "Company Name", "Job Title"]

  # validates_inclusion_of :job_type, :in => JOB_TYPE 
  # validates_inclusion_of :occupation, :in => OCCUPATION

  before_validation :set_aasm_state, :on => :create
  before_validation :set_deadline
  
  scope :published , where(:aasm_state => "published")
  scope :online, published.where("deadline is NULL or deadline > ?", Date.today )
  scope :order_by_date, :order => "id DESC"
  scope :order_by_company_name, :order => "company_name ASC"
  scope :order_by_job_title, :order => "title ASC"
  
  def open
    self.aasm_state = "published"
  end
  
  def close
    self.aasm_state = "closed"
  end
  
  def closed?
    self.aasm_state == "closed"
  end
  
  def expired
    return true if elapsed_date > 30
    return false;
  end

  def to_param
    "#{self.id}-#{self.title} #{self.company_name}".to_slug.normalize.to_s
  end
  
  def social_link_url
    CGI::escape "http://jobs.ruby.tw/jobs/#{self.to_param}"
  end
  
  def social_link_title
    CGI::escape self.title
  end
  
  def social_link_content
    "#{social_link_title} #{social_link_url}"
  end
  
  def deadline_forever
    @deadline_forever ||= !self.deadline
  end

  def owned_by?(user)
    user && owner == user
  end
  
  def elapsed
    diff = Time.now - self.updated_at
    days  = (diff / 1.day).round
    hours = (diff / 1.hour).round
    mins  = (diff / 1.minute).round

    if days > 0
      elapsed_time = "#{days} day"
      elapsed_time += "s" unless days == 1
    elsif hours > 0
      elapsed_time = "#{hours} hour"
      elapsed_time += "s" unless hours == 1
    else
      elapsed_time = "#{mins} minute"
      elapsed_time += "s" unless mins == 1
    end
    elapsed_time
  end

  def elapsed_date
    diff = Time.now - self.updated_at
    days = (diff / 1.day).round
    days
  end

  def highlighted
    return highlighted1 | highlighted2
  end

  def total_price
    price = 250;
    price += 50 if highlighted1 == true
    price += 30 if highlighted2 == true
    return price
  end

  private
  
  def set_deadline
    self.deadline = nil if self.deadline_forever == "1"
  end
     
  def set_aasm_state
    self.aasm_state = "trial"
  end
  
end

app/controllers/jobs_controller.rb
# -*- encoding : utf-8 -*-
class JobsController < ApplicationController

  # before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :find_my_job, only: [:preview, :publish, :edit, :update, :destroy, :open, :close, :restart]

  def index
    
    recover_session

    extract_queries

    if params[:order_by]
      session[:order_by] = params[:order_by]
      case params[:order_by]
      when "0"
        order_by = "jobs.id DESC"
      when "1"
        order_by = "jobs.company_name"
      when "2"
        order_by = "jobs.title"
      end
    else
      order_by = "id DESC"
    end

    if params[:keyword]
      session[:keyword] = params[:keyword]
      @jobs = Job.search(params[:keyword], nil, {order: order_by})
    elsif session[:keyword]
      @jobs = Job.search(session[:keyword], nil, {order: order_by})
    else
      @jobs = Job.order(order_by)
    end
    unless @job_types.empty?
      @jobs = @jobs.select { |job| @job_types.include? job.job_type.to_i }
    end

    respond_to do |format|
      format.json { render json: @jobs }
      format.html
      format.rss { render :layout => false } #index.rss.builder
    end
  end

  def show
    @job = Job.find(params[:id])

    set_page_title "#{@job.title} | #{@job.company_name} is hiring!"
    set_page_description @job.description
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(params[:job])
    puts @job.errors.inspect
    if @job.save
      redirect_to preview_job_path(@job)
    else
      render :new
    end
  end

  def edit
  end

  def preview
  end

  def publish
  end

  def payment
    # transcation(params[:stripe_token])
    redirect_to jobs_path
  end

  def update
    if @job.update_attributes(params[:job])
      redirect_to preview_job_path(@job)
    else
      render :edit
    end
  end

  def restart
    @job.updated_at = Time.now
    @job.save

    redirect_to "/admin"
  end

  def destroy
    @job.destroy

    redirect_to "/admin"
  end

  def open
    @job.open
    @job.save!

    redirect_to job_path(@job)
  end

  def close
    @job.close
    @job.save!

    redirect_to job_path(@job)
  end

  protected

  def find_my_job
    @job = Job.find(params[:id])
  end

  def transcation(token)
    @transcation = Stripe::Charge.create(
      :amount => 40000, # 40$
      :currency => "usd",
      :card => token,
      :description => "Charge for apptopia job posting"
    )
  end

  def recover_session
    if params[:order_by].nil?
      params[:order_by] = session[:order_by]
      
      if !session[:full_time].nil?
        params[:full_time] = session[:full_time].to_s
      end

      if !session[:part_time].nil?
        params[:part_time] = session[:part_time].to_s
      end

      if !session[:app_project].nil?
        params[:app_project] = session[:app_project].to_s
      end
    end

  end

  def extract_queries
    @job_types = Array.new

    if !params[:full_time].nil?
      @job_types.push 0
    end

    if !params[:part_time].nil?
      @job_types.push 1
    end

    if !params[:app_project].nil?
      @job_types.push 2 
    end
  
    session[:full_time] = params[:full_time]
    session[:part_time] = params[:part_time]
    session[:app_project] = params[:app_project]
  end

end

app/helpers/jobs_helper.rb
# -*- encoding : utf-8 -*-
module JobsHelper
	require 'uri'

	def show_tags(job)
		tags_html = "<li><a href='#' class='tech_tag'>#{Job::JOB_TYPE[job.job_type.to_i]}</a></li>";
		unless job.tags.nil?
			tags = job.tags.split(',')
			
			tags.each do |t|
				tags_html += "<li><a href='#' class='tech_tag'>#{t}</a></li>"
			end

		end
		return tags_html.html_safe
	end
# p[images][]=https://s3.amazonaws.com/apptopia.com/uploads/app/icon/37129/iD0ars9VZxyYmgb5k3nBCU0ZYNFApC4YC5FneKX8VX983e8nNAehH3ks3fBJ_csVLKs.png
	def link_to_facebook(job)
		# <a href="http://www.facebook.com/sharer.php?&amp;p[summary]=Want to acquire an app? (i.e. ownership, users, IP, etc) you should check out Outlook Web Mobile (OWA Email) via @apptopia!&amp;p[title]=Outlook Web Mobile (OWA Email) is on sale&amp;p[url]=http://www.apptopia.com/listings/outlook-web-mobile-owa-email&amp;s=100" class="fb" target="_blank">Share on Facebook</a>

		address_facebook = "https://www.facebook.com/sharer/sharer.php?"
		images = "&p[images][]=#{job.company_logo.url(:medium)}"
		summary = "&p[summary]=#{strip_tags job.description}"
		url = "&p[url]=#{request.original_url}"
		title = job.title + " - " + job.company_name
		title = "p[title]=#{title}"
		param_str = title + images + summary + url + "&s=100"
		facebook = content_tag :a, "<img src='/assets/social/facebook.png'>Share this job on facebook".html_safe, 
			:href => address_facebook + param_str, :target => '_blank'
	end

	def link_to_linkedin(job)
		address_linkedin = "http://www.linkedin.com/shareArticle?"
		summary = "&summary=#{job.company_name} is looking to hire a #{job.title}, you can see posting / apply here: #{request.original_url}"
		url = "&url=#{u request.original_url}"
		source = "&source=Apptopia"
		title= job.title + " - " + job.company_name
		title = "&title=#{title}"
		mini = "mini=true"
		param_str = mini + source + title + summary + url
		
		linked_in = content_tag :a, "<img src='/assets/social/linkedin.png'>Share this job on linkedin".html_safe, 
			:href => address_linkedin + param_str, :target => '_blank'
	end

	def link_to_twitter(job)
		address_twitter = "https://twitter.com/share?"
		text = "text=#{job.company_name} is looking to hire a #{job.title}, you can see posting / apply here: #{request.original_url}"
		# url = "url=#{request.original_url}"
		related = "&related=Apptopia"
		mini = "&mini=true"
		param_str = text + related + mini
		linked_in = content_tag :a, "<img src='/assets/social/twitter.png'>Tweet this".html_safe, 
			:href => address_twitter + param_str, :target => '_blank'
	end

	def mail_to(job)
		subject = "subject=#{job.company_name} is looking to hire a #{job.title}"
		body = "&body=#{job.company_name} is looking to hire a #{job.title}, you can see posting / apply here: #{request.original_url}"
		mail_addr = content_tag :a, "<img src='/assets/social/message.png'>Tell a friend".html_safe, 
			:href => "mailto:?#{subject}&#{body}"
	end

	def job_checked(job_type)
		return true if job_type == "1"
		return false
	end

	def job_index_page
		return true if controller.controller_name == "jobs" and params[:action] == "index"
	end
end

app/views/jobs/_form.mobile.erb
  <%= form_for @job do |f| %>

	<% if @job.errors.any? %>
	<div class="error_explanation">
  		<h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>
  		<ul>
  			<% @job.errors.full_messages.each do |msg| %>
    		<li><%= msg %></li>
  			<% end %>
  		</ul>
	</div>
	<% end %>

        <p>
          <%= f.label :title, t("job.title") %><br/>
	  <%= f.text_field :title, :class => "text" %>
        </p>
	
        <p>
          <%= f.label :company_name, t("job.company_name") %><br/>
	  <%= f.text_field :company_name, :class => "text" %>
        </p>
	
        <p>
          <%= f.label :url, "URL" %><br/>
	  <%= f.text_field :url, :class => "text" %>
        </p>
	
        <p>
          <%= f.label :job_type, t("job.type") %><br/>
		<% Job::JOB_TYPE.each do |t| %>
                        <%= f.radio_button :job_type, t %> <%= f.label :job_type, t, :value => t, :class => "inline" %>
		<% end %>
        </p>
	
        <p>
          <%= f.label :occupation, t("job.occupation") %><br/>
		<% Job::OCCUPATION.each do |o| %>
                        <%= f.radio_button :occupation, o %> <%= f.label :occupation, o, :value => o, :class => "inline" %>
		<% end %>
        </p>
		
        <p>
          <%= f.label :location, t("job.location") %><br/>
	  <%= f.text_field :location, :class => "text" %>
        </p>
	
        <p>
          <%= f.label :description, t("job.description") %><br/>
	  <%= f.text_area :description, :class => "text" %>
        </p>
	
        <p>
          <%= f.label :apply_information, t("job.apply_information") %><br/>
	  <%= f.text_area :apply_information, :class => "text" %>
        </p>
	
        <p>
          <%= f.label :deadline, t("job.deadline") %><br/>
          <span class="deadline_fields"><%= f.date_select :deadline %></span>
          <%= f.check_box :deadline_forever %><label for="job_deadline_forever" class="inner"><%= t("job.deadline_forever") %></label>
        </p>
	
        <p>
          <%= link_to(t(:preview), "#", :class => "jobpreview") %>
	  <%= f.submit t(:submit), :class => "submit button",:disable_with => t(:submiting) %>
        </p>
<% end %>

app/views/jobs/edit.mobile.erb
<div data-role="page">
  <header data-role="header">
    <h1><%= "Edit #{t("post_a_new_job")}" %></h1>
    <%= link_to 'Back', job_path(@job), "data-icon" => "arrow-l", "class" => "ui-btn-left" %>
    <%= link_to t(:delete), job_path(@job), :confirm => t(:are_you_sure), :method => :delete, "data-icon" => "delete", "class" => "ui-btn-right" %>
  </header>

  <div data-role="content">
    <%= render :partial => 'form', :object => @job %>
  </div><!-- content -->


  <footer data-role="footer">
    <h4>Ruby.tw</h4>
  </footer>
</div>

app/views/jobs/index.html.erb
<%= form_tag jobs_path, :id => "search-form", remote: true, :class => "navbar-search", :method => :get do %>
<div class="left-main-div">
	<div class="row-fluid">
		<div class="span6">
			<strong style="font-size: 26px;" id="jobs-count">
				<%= @jobs.length %> Jobs for developers
			</strong>
			<p class="gray">Latest post about <%= Job.last.elapsed if Job.all.present? %> ago</p>
		</div>
		
		<div id="sort-div" class="span3 pull-right">
			<br>
      <%= select_tag :order_by, 
        options_for_select(Job::SEARCH_TERMS.map.with_index{|i, m| [i, m]}, session[:order_by]), class: "selectpicker pull-right", data: {width: "150px"} %>
		</div>
	</div>
  <div id="job-list">
	<% @jobs.each_with_index do |job, i| %>
		<div class="row-fluid <%= 'highlighted' if job.highlighted == true %>">
			<div class="new-tag pull-left">
				<%= link_to 'NEW', '', :class => 'btn btn-u-mini' if job.elapsed_date < 6%>
			</div>
      <div class="span11 booking-blocks">
        <div style="overflow:hidden;">
        	<h4>
        		<%= link_to job.title, job_path(job), :style => 'float: left;' %>
        		<span class="hour pull-right light-gray"><%= job.elapsed %> ago</span>
        	</h4>
        	<br>
          <h5>
          	<strong><%= job.company_name %> - </strong>
          	<normal><%= job.location %></normal>
          </h5>
          <% description = strip_tags(job.description) %>
          <span class="light-gray ellipsis"><%= description%></span>
        </div>
        <div class="pull-left">
         	<ul class="inline blog-tags pull-left">
          	<%= show_tags(job) %>
          </ul>
        </div>
      </div>
    </div><!-- Row Fliud for each Job-->
    <%= "<hr>".html_safe if i != @jobs.length-1 %>
  <% end %>
  </div><!-- Job List Pane -->
</div><!-- Main content div -->
<div class="sidebar">
  <br>
  <a href="<%= new_job_path %>" class="btn-u post-job-btn">
    POST A JOB - <span style="font-size: 13px;">250$ for 30 days</span></a>
  <%= render :partial => "common/search_form" %>
</div><!-- Right Side Bar -->
<% end %>


<!-- Template Job Row -->
<div id="job-row-template" class="row-fluid" style="display: none;">
  <div class="new-tag pull-left">
    <a id="new-tag" class="btn btn-u-mini" href="">NEW</a>
  </div>
  <div class="span11">
    <div style="overflow:hidden;">
      <h4>
        <a id="title" style="float: left;" href="/jobs/3-ios-social-media-app-silverbiz"></a>
        <span id="elapsed" class="hour pull-right light-gray"></span>
      </h4>
      <br>
      <h5>
        <strong id="company_name"></strong>
        <normal id="location"></normal>
      </h5>
      <span class="light-gray ellipsis" id="description"></span>
    </div>
    <div class="pull-left">
      <ul class="inline blog-tags pull-left" id="tags">
        <li><a class="tech_tag" href="#">c#</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/jobs/index.mobile.erb
<div data-role="page">
  <header data-role="header" data-noBackBtn=true>
    <h1>Ruby Jobs in Taiwan</h1>
    <% if user_signed_in? %>
    <%= link_to 'Add', new_job_path, "data-icon" => "plus", "class" => "ui-btn-right" %>
    <% end %>
  </header>

  <div data-role="content">
    <ul data-role="listview">
      <% @jobs.each do |job| %>
      <li>
        <h3><%= link_to job.title, job_path(job) %></h3>
        <p><strong><%= job.company_name %></strong></p>
        <p><%= job.location %></p>
        <p class="ui-li-aside"><strong><%= job.created_at.to_date %></strong></p>
      </li>
      <% end %>
    </ul>
    <%= render "shared/foot" %>
  </div><!-- content -->


  <footer data-role="footer">
    <h4>Ruby.tw</h4>
  </footer>
</div>

app/views/jobs/new.mobile.erb
<div data-role="page">
  <header data-role="header">
    <h1><%= t("post_a_new_job") %></h1>
    <%= link_to 'Jobs', root_path, "data-icon" => "arrow-l", "class" => "ui-btn-left" %>
  </header>

  <div data-role="content">
    <%= render :partial => 'form', :object => @job %>
  </div><!-- content -->


  <footer data-role="footer">
    <h4>Ruby.tw</h4>
  </footer>
</div>

app/views/jobs/preview.html.erb
<div>
	<div class="widget-body">
		<div class="widget-main">
			<div class="row-fluid">
				<div id="fuelux-wizard" style="width: 50%; margin-left: -30px;" class="row-fluid" data-target="#step-container">
					<ul class="wizard-steps">
						<li onclick="location.href='<%= edit_job_path(@job) %>'" class="complete">
							<span class="step">1</span>
							<span class="title">Create</span>
						</li>

						<li class="active">
							<span class="step">2</span>
							<span class="title">Preview</span>
						</li>

						<li class="">
							<span class="step">3</span>
							<span class="title">Publish</span>
						</li>
					</ul>
				</div>
				<br>
				<h3 id="step-title">Step 2: Preview Your Posting</h3>
				<hr>
				<div class="row-fluid wizard-actions">
					<a class="btn-u btn-lightblue btn-medium" href="<%= publish_job_path(@job) %>">
						Continue to Step 3 to publish your posting
					</a>
					<a class="btn-small gray" href="<%= edit_job_path(@job) %>">
						 <img src="/assets/back-arrow.png"/>
						 Make changes
					</a>
				</div>
				<hr>
				<div class="step-content" id="step-container">
					<div class="step-pane active">
						<!-- Preview Content -->
						<div class="left-main-div">
							<div class="row-fluid">
								<div class="span8">
									<h2><%= @job.title %></h2>
									<h4>
								  	<strong><%= @job.company_name %></strong> - 
								  	<normal><%= @job.location %></normal>
								  </h4>

								  <p><%= link_to @job.url, @job.url %></p>
								  <div class="pull-left blog-page blog-item">
								   	<ul class="inline blog-tags pull-left">
								    	<%= show_tags(@job) %>
								    </ul>
								  </div>
								</div>
								<div class="span4">
									<%= image_tag @job.company_logo.url(:medium), :style => "margin-top:15px;" %>
								</div>
							</div>
						  <p>
						  	<%= @job.description.html_safe unless @job.description.nil? %>
						  </p>

						  <div class="alert apply-info">
						  	<h5>Apply for this position</h5>
						  	<p>
						  		<%= @job.apply_information.gsub("\n", "<br>").html_safe unless @job.apply_information == "" %>
						  	</p>
						  </div>

						  <div class="row-fluid wizard-actions">
								<a class="btn-u btn-lightblue btn-medium" href="<%= publish_job_path(@job) %>">
									Continue to Step 3 to publish your posting
								</a>
								<a class="btn-small gray" href="<%= edit_job_path(@job) %>">
									 <img src="/assets/back-arrow.png"/>
									 Make changes
								</a>
							</div>
						</div><!-- /Preview Content End -->
						<div class="sidebar share-with-social">
							<img src="/assets/preview_share.png" style="width: 270px">
						</div>
					</div>
				</div>
			</div>
		</div><!--/widget-main-->
	</div><!--/widget-body-->
</div>

app/views/jobs/publish.html.erb
<% content_for :head do %>
	<%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
<% end %>
<div>
	<div class="widget-body">
		<div class="widget-main">
			<div class="row-fluid">
				<div id="fuelux-wizard" style="width: 50%; margin-left: -30px;" class="row-fluid" data-target="#step-container">
					<ul class="wizard-steps">
						<li onclick="location.href='<%= edit_job_path(@job) %>'" class="complete">
							<span class="step">1</span>
							<span class="title">Create</span>
						</li>

						<li onclick="location.href='<%= preview_job_path(@job) %>'" class="complete">
							<span class="step">2</span>
							<span class="title">Preview</span>
						</li>

						<li data-target="#step3" class="active">
							<span class="step">3</span>
							<span class="title">Publish</span>
						</li>
					</ul>
				</div>
				<br>
				<h3 id="step-title">Step 3: Publish Your Posting</h3>
				<hr>
				<div class="step-content" id="step-container">
					<div class="step-pane active">
						<!-- Preview Content -->
						<div class="left-main-div">
							<form action="<%= payment_job_path(@job) %>" id="payment_form" method="post">
							<div class="row-fluid">
								<div class="span11">
									<div id="new-job-payment" class="form">
										<p class="ft22">Enter your billing information</p>
										<div class="alert alert-error" style="display:none" id="stripe_error"></div>
										<%= hidden_field_tag :stripe_token %>
										<div class="field">
											<%= label_tag :card_number, 'Card Number' %>
											<%= text_field_tag :card_number %>
											<img src="/assets/payment_method.jpg">
										</div>

										<div class="field">
											<%= label_tag :expiration, 'Expiration' %>
											<%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"}%>
								      <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+10}, {name: nil, id: "card_year"}%>
										</div>

										<div class="field">
											<%= label_tag :zipcode, "Zip/Postal Code" %>
											<%= text_field_tag :zipcode %>
										</div>

										<div class="field">
											<label for="ccvn">CCV</label>
											<%= text_field_tag :ccvn %>
									  </div>
									</div> <!-- #new-job-payment div end -->
								</div><!-- span11 end -->
							</div><!-- row-fluid end -->
						</div>
						<div class="row-fluid">
							<h4 style="margin-left: 10px; color:#000">
								Total price: $<%= @job.total_price %>
							</h4>
							<hr>
							<div class="span11 alert apply-info">
								<p>You are only permitted to post one job opening per ad (you cannot say “We have 4 open positions...”). This charge is non refundable. Apptopia.com reserves the right to deny or remove job posts at our discretion (we will refund your money if we don’t run your ad). If you have questions please send a message to Support@apptopia.com</p>
							</div><!-- Highlight guide -->
						</div>
						<div class="row-fluid" style="padding: 3px">
							<button type="submit" id="payment_submit" class="btn-u btn-lightblue btn-medium">
								Submit Payment & Publish Your Job
							</button>
							 or
							<a onclick="history.back();" class="gray">
								<img src="/assets/back-arrow.png"/>
								Make Changes
							</a>
							<br>
						</div>
					</div>
			</div>
		</div><!--/widget-main-->
	</div><!--/widget-body-->
</div>

app/views/jobs/show.html.erb
<%#= render_shareable :buttons => ['twitter', 'facebook', 'linkedin'] %>
<div class="left-main-div">
	<div class="row-fluid">
		<div class="span8">
			<h2><%= @job.title %></h2>
			<h4>
		  	<strong><%= @job.company_name %></strong> - 
		  	<normal><%= @job.location %></normal>
		  </h4>

		  <p><%= link_to @job.url, @job.url %></p>
		  <div class="pull-left blog-page blog-item">
		   	<ul class="inline blog-tags pull-left">
		    	<%= show_tags(@job) %>
		    </ul>
		  </div>
		</div>
		<div class="span4">
			<%= image_tag @job.company_logo.url(:medium), :style => "margin-top:15px;" %>
		</div>
	</div>
  <p>
  	<%= @job.description.html_safe unless @job.description.nil? %>
  </p>

  <div class="alert apply-info">
  	<h5>Apply for this position</h5>
  	<p>
  		<%= @job.apply_information.gsub("\n", "<br>").html_safe unless @job.apply_information == "" %>
  	</p>
  </div>
</div>
<div class="sidebar share-with-social">
	<a href="<%= new_job_path %>" class="btn-u post-job-btn">
		POST A JOB - <span style="font-size: 13px;">250$ for 30 days</span>
	</a>
	<p>
		<%= link_to_facebook(@job) %>
	<!-- 
		<a 
			onclick="
    	window.open(
      'https://www.facebook.com/sharer/sharer.php?p[url]='+encodeURIComponent(location.href) + '&p[title]=this', 
      'facebook-share-dialog', 
      'width=626,height=436'); 
    	return false;">
    	<img src="/assets/social/facebook.png">
  		Share this job on facebook
  	</a> -->
  	<a href=""
  </p>
	<p>
		<%= link_to_twitter(@job) %>
	</p>
	<p>
		<%= link_to_linkedin(@job) %>
	</p>
	<p>
		<%= mail_to(@job) %>
	</p>
</div>

app/views/jobs/show.mobile.erb
<div data-role="page">
  <header data-role="header">
    <h1><%= @job.title %></h1>
    <%= link_to 'Jobs', root_path, "data-icon" => "arrow-l", "class" => "ui-btn-left" %>
    <% if @job.owner == current_user %>
    <%= link_to 'Edit', edit_job_path(@job), "data-icon" => "edit", "class" => "ui-btn-right" %>
    <% end %>
  </header>

  <div data-role="content">
    <%= render :partial => "job", :object => @job %>
    <%= render "shared/foot" %>
  </div><!-- content -->

  <footer data-role="footer">
    <h4>Ruby.tw</h4>
  </footer>
</div>