config/routes.rb
# -*- encoding : utf-8 -*-
JobsApptopia::Application.routes.draw do
  
  match '/about' => 'pages#about', :as => "about"
  
  devise_for :users

  resources :jobs do
    member do
      put :open
      put :close
      put :restart
      get :preview
      get :publish
      post :payment
    end
  end

  resources :admin do
    member do
      get :dashboard
    end
  end

  root :to => "jobs#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
  
  match "*path" => "pages#404"
end

app/views/common/_facebook_js.erb
<!-- 
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/zh_TW/all.js#xfbml=1&appId=174126862200";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
 -->

app/views/common/_google_analytics.html.erb
<script type="text/javascript">

//   var _gaq = _gaq || [];
//   _gaq.push(['_setAccount', 'UA-145330-14']);
//   _gaq.push(['_trackPageview']);

//   (function() {
//     var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
//     ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
//     var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
//   })();

</script>

app/views/common/_search_form.html.erb
<%= text_field_tag :keyword, session[:keyword], :placeholder => 'Search: ‘Boston’, ‘Unity’, ‘Android’…' %>
<div id="search-jobtype">
	<label>
		<%= check_box_tag :full_time, 1, job_checked(session[:full_time]) %>
		Full-time
	</label>
	<label>
		<%= check_box_tag :part_time, 1, job_checked(session[:part_time]) %>
		Part-time
	</label>
	<label>
		<%= check_box_tag :app_project, 1, job_checked(session[:app_project]) %>
		App project
	</label>
	<br>
</div>
<a class="rss-feed" href="/jobs.rss">
	Subscribe RSS feed to find out when new jobs are posted
</a>

app/views/common/_usernav.html.erb
<% if user_signed_in? %>
  Hi, <%= current_user.email %> 
  <%#= link_to t(:list_my_posting), jobs_path(current_user, :user_id => current_user) %> | 
  <%= link_to t(:settings), edit_user_registration_path %> |
  <%= link_to t(:logout), destroy_user_session_path, :method => :delete %>
<% else %>
  <%= link_to t(:home), "/" %>
<% end %>